services:
  app:
    build:
      context: .
      dockerfile: go.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  # redis:
  #   image: "redis"
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"

  postgresql:
    image: postgres 
    # restart: always
    ports:
      - "5432:5432"
    user: postgres  
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - "POSTGRES_DB=tinybin"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_HOST_AUTH_METHOD=scram-sha-256"
      - "POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256"
      - "PGDATA=/var/lib/postgresql/data/pgdata"

volumes:
  postgres: 
